# Generated by Django 2.1.7 on 2019-03-14 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20170307_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
